import type { JobListing } from "./types.js";

/**
 * Local/fixture data only — not served on the public site.
 * Live inventory comes from Supabase (employer posts + feed sync).
 */
export const SAMPLE_JOBS: JobListing[] = [
  {
    id: "1",
    slug: "registered-nurse-manchester-nhs",
    title: "Registered Nurse (Band 5)",
    employerId: "emp-1",
    employerName: "Manchester NHS Trust",
    description:
      "Join our acute medical ward team at Manchester Royal Infirmary. NMC registration required. You will assess patients, administer medication, and work within a multidisciplinary team. Excellent development opportunities including Band 6 progression pathways.",
    location: "Manchester Royal Infirmary",
    city: "Manchester",
    region: "North West",
    postcode: "M13 9WL",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 28407, max: 34581, currency: "GBP", period: "year", disclosed: true },
    skills: ["NMC", "Acute care", "Patient assessment"],
    status: "active",
    featured: true,
    applicationCount: 12,
    publishedAt: "2026-07-15T09:00:00Z",
    expiresAt: "2026-08-14T09:00:00Z",
  },
  {
    id: "2",
    slug: "care-assistant-birmingham",
    title: "Care Assistant",
    employerId: "emp-2",
    employerName: "Sunrise Care Homes",
    description:
      "Support residents with daily living in our CQC-rated Good home in Edgbaston. Full training provided including manual handling and dementia care. Enhanced DBS required. Flexible shift patterns available.",
    location: "Edgbaston",
    city: "Birmingham",
    region: "West Midlands",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 12.5, max: 13.5, currency: "GBP", period: "hour", disclosed: true },
    skills: ["Personal care", "Manual handling", "Dementia care"],
    status: "active",
    featured: false,
    applicationCount: 34,
    publishedAt: "2026-07-18T09:00:00Z",
    expiresAt: "2026-08-17T09:00:00Z",
  },
  {
    id: "3",
    slug: "electrician-london-contract",
    title: "Electrician (ECS Gold Card)",
    employerId: "emp-3",
    employerName: "BuildRight Contractors",
    description:
      "Commercial fit-out projects across Central London. CIS registered. 6-month contract with potential extension. ECS Gold Card and 18th Edition required.",
    location: "Central London",
    city: "London",
    region: "London",
    remote: "onsite",
    jobType: "contract",
    vertical: "trades",
    salary: { min: 220, max: 260, currency: "GBP", period: "day", disclosed: true },
    skills: ["ECS Gold", "18th Edition", "Commercial wiring"],
    status: "active",
    featured: false,
    applicationCount: 8,
    publishedAt: "2026-07-20T09:00:00Z",
    expiresAt: "2026-08-19T09:00:00Z",
  },
  {
    id: "4",
    slug: "hca-leeds-nhs-trust",
    title: "Healthcare Assistant (HCA)",
    employerId: "emp-4",
    employerName: "Leeds Teaching Hospitals NHS Trust",
    description:
      "Band 2 HCA required for busy surgical ward. Support registered nurses with patient care, observations, and ward housekeeping. Previous healthcare experience preferred. Enhanced DBS essential.",
    location: "St James's University Hospital",
    city: "Leeds",
    region: "Yorkshire",
    postcode: "LS9 7TF",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 23195, max: 23195, currency: "GBP", period: "year", disclosed: true },
    skills: ["Vital signs", "Patient hygiene", "Ward support"],
    status: "active",
    featured: true,
    applicationCount: 47,
    publishedAt: "2026-07-10T09:00:00Z",
    expiresAt: "2026-08-09T09:00:00Z",
  },
  {
    id: "5",
    slug: "support-worker-bristol",
    title: "Support Worker — Learning Disabilities",
    employerId: "emp-5",
    employerName: "Brighter Futures Care",
    description:
      "Community-based support for adults with learning disabilities in Bristol. Full UK driving licence preferred. Person-centred care approach. Enhanced DBS and right to work in UK required.",
    location: "South Bristol",
    city: "Bristol",
    region: "South West",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 12.21, max: 13.0, currency: "GBP", period: "hour", disclosed: true },
    skills: ["Learning disabilities", "Community care", "Personal care"],
    status: "active",
    featured: false,
    applicationCount: 19,
    publishedAt: "2026-07-12T09:00:00Z",
    expiresAt: "2026-08-11T09:00:00Z",
  },
  {
    id: "6",
    slug: "rmn-nottingham-band-6",
    title: "Registered Mental Health Nurse (Band 6)",
    employerId: "emp-6",
    employerName: "Nottinghamshire Healthcare NHS Foundation Trust",
    description:
      "RMN required for acute inpatient mental health unit. NMC registration essential. Experience with Mental Health Act assessments and risk management. Rotation includes community liaison.",
    location: "Mapperley Hospital",
    city: "Nottingham",
    region: "East Midlands",
    postcode: "NG3 6AA",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 35392, max: 42618, currency: "GBP", period: "year", disclosed: true },
    skills: ["NMC", "Mental health act", "Risk assessment"],
    status: "active",
    featured: false,
    applicationCount: 6,
    publishedAt: "2026-07-08T09:00:00Z",
    expiresAt: "2026-08-07T09:00:00Z",
  },
  {
    id: "7",
    slug: "physiotherapist-cambridge",
    title: "Physiotherapist — MSK Outpatients",
    employerId: "emp-7",
    employerName: "Cambridge University Hospitals",
    description:
      "HCPC-registered physiotherapist for busy MSK outpatient department. Experience with orthopaedic post-op rehabilitation. Band 6 equivalent. Hybrid admin days available.",
    location: "Addenbrooke's Hospital",
    city: "Cambridge",
    region: "East of England",
    postcode: "CB2 0QQ",
    remote: "hybrid",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 35392, max: 42618, currency: "GBP", period: "year", disclosed: true },
    skills: ["HCPC", "MSK", "Rehabilitation"],
    status: "active",
    featured: false,
    applicationCount: 11,
    publishedAt: "2026-07-14T09:00:00Z",
    expiresAt: "2026-08-13T09:00:00Z",
  },
  {
    id: "8",
    slug: "plumber-manchester-self-employed",
    title: "Plumber — Domestic & Commercial",
    employerId: "emp-8",
    employerName: "NorthWest Plumbing Services",
    description:
      "Experienced plumber for domestic and light commercial work across Greater Manchester. Gas Safe registration required. Self-employed or PAYE options. Van and tools provided.",
    location: "Greater Manchester",
    city: "Manchester",
    region: "North West",
    remote: "onsite",
    jobType: "contract",
    vertical: "trades",
    salary: { min: 180, max: 220, currency: "GBP", period: "day", disclosed: true },
    skills: ["Gas Safe", "Boiler installation", "Commercial plumbing"],
    status: "active",
    featured: false,
    applicationCount: 15,
    publishedAt: "2026-07-16T09:00:00Z",
    expiresAt: "2026-08-15T09:00:00Z",
  },
  {
    id: "9",
    slug: "software-engineer-london-remote",
    title: "Software Engineer (TypeScript)",
    employerId: "emp-9",
    employerName: "FinTech Scale-up",
    description:
      "Mid-level software engineer to join a growing fintech team. TypeScript, React, Node.js. Fully remote within UK. Equity package available.",
    location: "Remote — UK",
    city: "London",
    region: "London",
    remote: "remote",
    jobType: "permanent",
    vertical: "tech",
    salary: { min: 55000, max: 75000, currency: "GBP", period: "year", disclosed: true },
    skills: ["TypeScript", "React", "Node.js"],
    status: "active",
    featured: true,
    applicationCount: 89,
    publishedAt: "2026-07-19T09:00:00Z",
    expiresAt: "2026-08-18T09:00:00Z",
  },
  {
    id: "10",
    slug: "care-assistant-glasgow",
    title: "Care Assistant — Residential",
    employerId: "emp-10",
    employerName: "Caledonia Care Group",
    description:
      "Support residents in a CQC-rated Good care home in Glasgow's West End. Full training provided. Enhanced DBS required. Permanent and bank shifts available.",
    location: "West End",
    city: "Glasgow",
    region: "Scotland",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 12.5, max: 13.2, currency: "GBP", period: "hour", disclosed: true },
    skills: ["Personal care", "Manual handling", "Medication support"],
    status: "active",
    featured: false,
    applicationCount: 22,
    publishedAt: "2026-07-21T09:00:00Z",
    expiresAt: "2026-08-20T09:00:00Z",
  },
  {
    id: "11",
    slug: "registered-nurse-liverpool-band-5",
    title: "Registered Nurse (Band 5) — A&E",
    employerId: "emp-11",
    employerName: "Liverpool University Hospitals NHS Foundation Trust",
    description:
      "Band 5 RN for busy A&E department at Royal Liverpool University Hospital. NMC registration required. Preceptorship available for newly qualified nurses.",
    location: "Royal Liverpool University Hospital",
    city: "Liverpool",
    region: "North West",
    remote: "onsite",
    jobType: "permanent",
    vertical: "healthcare",
    salary: { min: 28407, max: 34581, currency: "GBP", period: "year", disclosed: true },
    skills: ["NMC", "A&E", "Triage"],
    status: "active",
    featured: true,
    applicationCount: 31,
    publishedAt: "2026-07-20T09:00:00Z",
    expiresAt: "2026-08-19T09:00:00Z",
  },
  {
    id: "12",
    slug: "site-manager-sheffield",
    title: "Site Manager — Construction",
    employerId: "emp-12",
    employerName: "Yorkshire Build Ltd",
    description:
      "SMSTS-qualified site manager for residential development projects across South Yorkshire. CSCS Black Manager card required. Package includes company vehicle.",
    location: "South Yorkshire",
    city: "Sheffield",
    region: "Yorkshire",
    remote: "onsite",
    jobType: "permanent",
    vertical: "trades",
    salary: { min: 45000, max: 55000, currency: "GBP", period: "year", disclosed: true },
    skills: ["SMSTS", "CSCS Black", "Residential"],
    status: "active",
    featured: false,
    applicationCount: 9,
    publishedAt: "2026-07-17T09:00:00Z",
    expiresAt: "2026-08-16T09:00:00Z",
  },
  {
    id: "13",
    slug: "devops-engineer-glasgow",
    title: "DevOps Engineer",
    employerId: "emp-13",
    employerName: "Scottish FinTech Ltd",
    description:
      "DevOps engineer to manage AWS infrastructure for a growing fintech. Terraform, Kubernetes, CI/CD. Hybrid — 2 days in Glasgow city centre.",
    location: "Glasgow City Centre",
    city: "Glasgow",
    region: "Scotland",
    remote: "hybrid",
    jobType: "permanent",
    vertical: "tech",
    salary: { min: 50000, max: 65000, currency: "GBP", period: "year", disclosed: true },
    skills: ["AWS", "Terraform", "Kubernetes"],
    status: "active",
    featured: false,
    applicationCount: 42,
    publishedAt: "2026-07-18T09:00:00Z",
    expiresAt: "2026-08-17T09:00:00Z",
  },
  {
    id: "14",
    slug: "warehouse-operative-liverpool",
    title: "Warehouse Operative",
    employerId: "emp-14",
    employerName: "Mersey Logistics",
    description:
      "Warehouse operative for distribution centre near Liverpool docks. FLT licence advantageous. Day and night shifts available. Immediate start.",
    location: "Bootle",
    city: "Liverpool",
    region: "North West",
    remote: "onsite",
    jobType: "permanent",
    vertical: "general",
    salary: { min: 12.21, max: 14.0, currency: "GBP", period: "hour", disclosed: true },
    skills: ["Manual handling", "Pick and pack", "FLT"],
    status: "active",
    featured: false,
    applicationCount: 56,
    publishedAt: "2026-07-21T08:00:00Z",
    expiresAt: "2026-08-20T09:00:00Z",
  },
];
